
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Admin
 * 
 */
export type Admin = Prisma.AdminModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Industry
 * 
 */
export type Industry = Prisma.IndustryModel
/**
 * Model BoxStyle
 * 
 */
export type BoxStyle = Prisma.BoxStyleModel
/**
 * Model Material
 * 
 */
export type Material = Prisma.MaterialModel
/**
 * Model Finish
 * 
 */
export type Finish = Prisma.FinishModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductImage
 * 
 */
export type ProductImage = Prisma.ProductImageModel
/**
 * Model QuoteRequest
 * 
 */
export type QuoteRequest = Prisma.QuoteRequestModel
