
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Admin.ts'
export type * from './models/Category.ts'
export type * from './models/Industry.ts'
export type * from './models/BoxStyle.ts'
export type * from './models/Material.ts'
export type * from './models/Finish.ts'
export type * from './models/Product.ts'
export type * from './models/ProductImage.ts'
export type * from './models/QuoteRequest.ts'
export type * from './commonInputTypes.ts'