
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `BoxStyle` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model BoxStyle
 * 
 */
export type BoxStyleModel = runtime.Types.Result.DefaultSelection<Prisma.$BoxStylePayload>

export type AggregateBoxStyle = {
  _count: BoxStyleCountAggregateOutputType | null
  _min: BoxStyleMinAggregateOutputType | null
  _max: BoxStyleMaxAggregateOutputType | null
}

export type BoxStyleMinAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BoxStyleMaxAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BoxStyleCountAggregateOutputType = {
  id: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BoxStyleMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type BoxStyleMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type BoxStyleCountAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BoxStyleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BoxStyle to aggregate.
   */
  where?: Prisma.BoxStyleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BoxStyles to fetch.
   */
  orderBy?: Prisma.BoxStyleOrderByWithRelationInput | Prisma.BoxStyleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BoxStyleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BoxStyles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BoxStyles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BoxStyles
  **/
  _count?: true | BoxStyleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BoxStyleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BoxStyleMaxAggregateInputType
}

export type GetBoxStyleAggregateType<T extends BoxStyleAggregateArgs> = {
      [P in keyof T & keyof AggregateBoxStyle]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBoxStyle[P]>
    : Prisma.GetScalarType<T[P], AggregateBoxStyle[P]>
}




export type BoxStyleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BoxStyleWhereInput
  orderBy?: Prisma.BoxStyleOrderByWithAggregationInput | Prisma.BoxStyleOrderByWithAggregationInput[]
  by: Prisma.BoxStyleScalarFieldEnum[] | Prisma.BoxStyleScalarFieldEnum
  having?: Prisma.BoxStyleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BoxStyleCountAggregateInputType | true
  _min?: BoxStyleMinAggregateInputType
  _max?: BoxStyleMaxAggregateInputType
}

export type BoxStyleGroupByOutputType = {
  id: string
  name: string
  createdAt: Date
  updatedAt: Date
  _count: BoxStyleCountAggregateOutputType | null
  _min: BoxStyleMinAggregateOutputType | null
  _max: BoxStyleMaxAggregateOutputType | null
}

type GetBoxStyleGroupByPayload<T extends BoxStyleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BoxStyleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BoxStyleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BoxStyleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BoxStyleGroupByOutputType[P]>
      }
    >
  >



export type BoxStyleWhereInput = {
  AND?: Prisma.BoxStyleWhereInput | Prisma.BoxStyleWhereInput[]
  OR?: Prisma.BoxStyleWhereInput[]
  NOT?: Prisma.BoxStyleWhereInput | Prisma.BoxStyleWhereInput[]
  id?: Prisma.UuidFilter<"BoxStyle"> | string
  name?: Prisma.StringFilter<"BoxStyle"> | string
  createdAt?: Prisma.DateTimeFilter<"BoxStyle"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BoxStyle"> | Date | string
  products?: Prisma.ProductListRelationFilter
}

export type BoxStyleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  products?: Prisma.ProductOrderByRelationAggregateInput
}

export type BoxStyleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.BoxStyleWhereInput | Prisma.BoxStyleWhereInput[]
  OR?: Prisma.BoxStyleWhereInput[]
  NOT?: Prisma.BoxStyleWhereInput | Prisma.BoxStyleWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"BoxStyle"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BoxStyle"> | Date | string
  products?: Prisma.ProductListRelationFilter
}, "id" | "name">

export type BoxStyleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BoxStyleCountOrderByAggregateInput
  _max?: Prisma.BoxStyleMaxOrderByAggregateInput
  _min?: Prisma.BoxStyleMinOrderByAggregateInput
}

export type BoxStyleScalarWhereWithAggregatesInput = {
  AND?: Prisma.BoxStyleScalarWhereWithAggregatesInput | Prisma.BoxStyleScalarWhereWithAggregatesInput[]
  OR?: Prisma.BoxStyleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BoxStyleScalarWhereWithAggregatesInput | Prisma.BoxStyleScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"BoxStyle"> | string
  name?: Prisma.StringWithAggregatesFilter<"BoxStyle"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BoxStyle"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BoxStyle"> | Date | string
}

export type BoxStyleCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutBoxStyleInput
}

export type BoxStyleUncheckedCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutBoxStyleInput
}

export type BoxStyleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutBoxStyleNestedInput
}

export type BoxStyleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUncheckedUpdateManyWithoutBoxStyleNestedInput
}

export type BoxStyleCreateManyInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BoxStyleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BoxStyleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BoxStyleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BoxStyleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BoxStyleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BoxStyleScalarRelationFilter = {
  is?: Prisma.BoxStyleWhereInput
  isNot?: Prisma.BoxStyleWhereInput
}

export type BoxStyleCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.BoxStyleCreateWithoutProductsInput, Prisma.BoxStyleUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.BoxStyleCreateOrConnectWithoutProductsInput
  connect?: Prisma.BoxStyleWhereUniqueInput
}

export type BoxStyleUpdateOneRequiredWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.BoxStyleCreateWithoutProductsInput, Prisma.BoxStyleUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.BoxStyleCreateOrConnectWithoutProductsInput
  upsert?: Prisma.BoxStyleUpsertWithoutProductsInput
  connect?: Prisma.BoxStyleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BoxStyleUpdateToOneWithWhereWithoutProductsInput, Prisma.BoxStyleUpdateWithoutProductsInput>, Prisma.BoxStyleUncheckedUpdateWithoutProductsInput>
}

export type BoxStyleCreateWithoutProductsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BoxStyleUncheckedCreateWithoutProductsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BoxStyleCreateOrConnectWithoutProductsInput = {
  where: Prisma.BoxStyleWhereUniqueInput
  create: Prisma.XOR<Prisma.BoxStyleCreateWithoutProductsInput, Prisma.BoxStyleUncheckedCreateWithoutProductsInput>
}

export type BoxStyleUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.BoxStyleUpdateWithoutProductsInput, Prisma.BoxStyleUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.BoxStyleCreateWithoutProductsInput, Prisma.BoxStyleUncheckedCreateWithoutProductsInput>
  where?: Prisma.BoxStyleWhereInput
}

export type BoxStyleUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.BoxStyleWhereInput
  data: Prisma.XOR<Prisma.BoxStyleUpdateWithoutProductsInput, Prisma.BoxStyleUncheckedUpdateWithoutProductsInput>
}

export type BoxStyleUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BoxStyleUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BoxStyleCountOutputType
 */

export type BoxStyleCountOutputType = {
  products: number
}

export type BoxStyleCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | BoxStyleCountOutputTypeCountProductsArgs
}

/**
 * BoxStyleCountOutputType without action
 */
export type BoxStyleCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyleCountOutputType
   */
  select?: Prisma.BoxStyleCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BoxStyleCountOutputType without action
 */
export type BoxStyleCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}


export type BoxStyleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  products?: boolean | Prisma.BoxStyle$productsArgs<ExtArgs>
  _count?: boolean | Prisma.BoxStyleCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["boxStyle"]>

export type BoxStyleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["boxStyle"]>

export type BoxStyleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["boxStyle"]>

export type BoxStyleSelectScalar = {
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BoxStyleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["boxStyle"]>
export type BoxStyleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | Prisma.BoxStyle$productsArgs<ExtArgs>
  _count?: boolean | Prisma.BoxStyleCountOutputTypeDefaultArgs<ExtArgs>
}
export type BoxStyleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type BoxStyleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $BoxStylePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BoxStyle"
  objects: {
    products: Prisma.$ProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["boxStyle"]>
  composites: {}
}

export type BoxStyleGetPayload<S extends boolean | null | undefined | BoxStyleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BoxStylePayload, S>

export type BoxStyleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BoxStyleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BoxStyleCountAggregateInputType | true
  }

export interface BoxStyleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BoxStyle'], meta: { name: 'BoxStyle' } }
  /**
   * Find zero or one BoxStyle that matches the filter.
   * @param {BoxStyleFindUniqueArgs} args - Arguments to find a BoxStyle
   * @example
   * // Get one BoxStyle
   * const boxStyle = await prisma.boxStyle.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BoxStyleFindUniqueArgs>(args: Prisma.SelectSubset<T, BoxStyleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BoxStyleClient<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BoxStyle that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BoxStyleFindUniqueOrThrowArgs} args - Arguments to find a BoxStyle
   * @example
   * // Get one BoxStyle
   * const boxStyle = await prisma.boxStyle.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BoxStyleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BoxStyleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BoxStyleClient<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BoxStyle that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BoxStyleFindFirstArgs} args - Arguments to find a BoxStyle
   * @example
   * // Get one BoxStyle
   * const boxStyle = await prisma.boxStyle.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BoxStyleFindFirstArgs>(args?: Prisma.SelectSubset<T, BoxStyleFindFirstArgs<ExtArgs>>): Prisma.Prisma__BoxStyleClient<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BoxStyle that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BoxStyleFindFirstOrThrowArgs} args - Arguments to find a BoxStyle
   * @example
   * // Get one BoxStyle
   * const boxStyle = await prisma.boxStyle.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BoxStyleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BoxStyleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BoxStyleClient<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BoxStyles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BoxStyleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BoxStyles
   * const boxStyles = await prisma.boxStyle.findMany()
   * 
   * // Get first 10 BoxStyles
   * const boxStyles = await prisma.boxStyle.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const boxStyleWithIdOnly = await prisma.boxStyle.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BoxStyleFindManyArgs>(args?: Prisma.SelectSubset<T, BoxStyleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BoxStyle.
   * @param {BoxStyleCreateArgs} args - Arguments to create a BoxStyle.
   * @example
   * // Create one BoxStyle
   * const BoxStyle = await prisma.boxStyle.create({
   *   data: {
   *     // ... data to create a BoxStyle
   *   }
   * })
   * 
   */
  create<T extends BoxStyleCreateArgs>(args: Prisma.SelectSubset<T, BoxStyleCreateArgs<ExtArgs>>): Prisma.Prisma__BoxStyleClient<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BoxStyles.
   * @param {BoxStyleCreateManyArgs} args - Arguments to create many BoxStyles.
   * @example
   * // Create many BoxStyles
   * const boxStyle = await prisma.boxStyle.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BoxStyleCreateManyArgs>(args?: Prisma.SelectSubset<T, BoxStyleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BoxStyles and returns the data saved in the database.
   * @param {BoxStyleCreateManyAndReturnArgs} args - Arguments to create many BoxStyles.
   * @example
   * // Create many BoxStyles
   * const boxStyle = await prisma.boxStyle.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BoxStyles and only return the `id`
   * const boxStyleWithIdOnly = await prisma.boxStyle.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BoxStyleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BoxStyleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BoxStyle.
   * @param {BoxStyleDeleteArgs} args - Arguments to delete one BoxStyle.
   * @example
   * // Delete one BoxStyle
   * const BoxStyle = await prisma.boxStyle.delete({
   *   where: {
   *     // ... filter to delete one BoxStyle
   *   }
   * })
   * 
   */
  delete<T extends BoxStyleDeleteArgs>(args: Prisma.SelectSubset<T, BoxStyleDeleteArgs<ExtArgs>>): Prisma.Prisma__BoxStyleClient<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BoxStyle.
   * @param {BoxStyleUpdateArgs} args - Arguments to update one BoxStyle.
   * @example
   * // Update one BoxStyle
   * const boxStyle = await prisma.boxStyle.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BoxStyleUpdateArgs>(args: Prisma.SelectSubset<T, BoxStyleUpdateArgs<ExtArgs>>): Prisma.Prisma__BoxStyleClient<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BoxStyles.
   * @param {BoxStyleDeleteManyArgs} args - Arguments to filter BoxStyles to delete.
   * @example
   * // Delete a few BoxStyles
   * const { count } = await prisma.boxStyle.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BoxStyleDeleteManyArgs>(args?: Prisma.SelectSubset<T, BoxStyleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BoxStyles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BoxStyleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BoxStyles
   * const boxStyle = await prisma.boxStyle.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BoxStyleUpdateManyArgs>(args: Prisma.SelectSubset<T, BoxStyleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BoxStyles and returns the data updated in the database.
   * @param {BoxStyleUpdateManyAndReturnArgs} args - Arguments to update many BoxStyles.
   * @example
   * // Update many BoxStyles
   * const boxStyle = await prisma.boxStyle.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BoxStyles and only return the `id`
   * const boxStyleWithIdOnly = await prisma.boxStyle.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BoxStyleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BoxStyleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BoxStyle.
   * @param {BoxStyleUpsertArgs} args - Arguments to update or create a BoxStyle.
   * @example
   * // Update or create a BoxStyle
   * const boxStyle = await prisma.boxStyle.upsert({
   *   create: {
   *     // ... data to create a BoxStyle
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BoxStyle we want to update
   *   }
   * })
   */
  upsert<T extends BoxStyleUpsertArgs>(args: Prisma.SelectSubset<T, BoxStyleUpsertArgs<ExtArgs>>): Prisma.Prisma__BoxStyleClient<runtime.Types.Result.GetResult<Prisma.$BoxStylePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BoxStyles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BoxStyleCountArgs} args - Arguments to filter BoxStyles to count.
   * @example
   * // Count the number of BoxStyles
   * const count = await prisma.boxStyle.count({
   *   where: {
   *     // ... the filter for the BoxStyles we want to count
   *   }
   * })
  **/
  count<T extends BoxStyleCountArgs>(
    args?: Prisma.Subset<T, BoxStyleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BoxStyleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BoxStyle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BoxStyleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BoxStyleAggregateArgs>(args: Prisma.Subset<T, BoxStyleAggregateArgs>): Prisma.PrismaPromise<GetBoxStyleAggregateType<T>>

  /**
   * Group by BoxStyle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BoxStyleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BoxStyleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BoxStyleGroupByArgs['orderBy'] }
      : { orderBy?: BoxStyleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BoxStyleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBoxStyleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BoxStyle model
 */
readonly fields: BoxStyleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BoxStyle.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BoxStyleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  products<T extends Prisma.BoxStyle$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BoxStyle$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BoxStyle model
 */
export interface BoxStyleFieldRefs {
  readonly id: Prisma.FieldRef<"BoxStyle", 'String'>
  readonly name: Prisma.FieldRef<"BoxStyle", 'String'>
  readonly createdAt: Prisma.FieldRef<"BoxStyle", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BoxStyle", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BoxStyle findUnique
 */
export type BoxStyleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * Filter, which BoxStyle to fetch.
   */
  where: Prisma.BoxStyleWhereUniqueInput
}

/**
 * BoxStyle findUniqueOrThrow
 */
export type BoxStyleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * Filter, which BoxStyle to fetch.
   */
  where: Prisma.BoxStyleWhereUniqueInput
}

/**
 * BoxStyle findFirst
 */
export type BoxStyleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * Filter, which BoxStyle to fetch.
   */
  where?: Prisma.BoxStyleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BoxStyles to fetch.
   */
  orderBy?: Prisma.BoxStyleOrderByWithRelationInput | Prisma.BoxStyleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BoxStyles.
   */
  cursor?: Prisma.BoxStyleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BoxStyles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BoxStyles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BoxStyles.
   */
  distinct?: Prisma.BoxStyleScalarFieldEnum | Prisma.BoxStyleScalarFieldEnum[]
}

/**
 * BoxStyle findFirstOrThrow
 */
export type BoxStyleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * Filter, which BoxStyle to fetch.
   */
  where?: Prisma.BoxStyleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BoxStyles to fetch.
   */
  orderBy?: Prisma.BoxStyleOrderByWithRelationInput | Prisma.BoxStyleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BoxStyles.
   */
  cursor?: Prisma.BoxStyleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BoxStyles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BoxStyles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BoxStyles.
   */
  distinct?: Prisma.BoxStyleScalarFieldEnum | Prisma.BoxStyleScalarFieldEnum[]
}

/**
 * BoxStyle findMany
 */
export type BoxStyleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * Filter, which BoxStyles to fetch.
   */
  where?: Prisma.BoxStyleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BoxStyles to fetch.
   */
  orderBy?: Prisma.BoxStyleOrderByWithRelationInput | Prisma.BoxStyleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BoxStyles.
   */
  cursor?: Prisma.BoxStyleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BoxStyles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BoxStyles.
   */
  skip?: number
  distinct?: Prisma.BoxStyleScalarFieldEnum | Prisma.BoxStyleScalarFieldEnum[]
}

/**
 * BoxStyle create
 */
export type BoxStyleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * The data needed to create a BoxStyle.
   */
  data: Prisma.XOR<Prisma.BoxStyleCreateInput, Prisma.BoxStyleUncheckedCreateInput>
}

/**
 * BoxStyle createMany
 */
export type BoxStyleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BoxStyles.
   */
  data: Prisma.BoxStyleCreateManyInput | Prisma.BoxStyleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BoxStyle createManyAndReturn
 */
export type BoxStyleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * The data used to create many BoxStyles.
   */
  data: Prisma.BoxStyleCreateManyInput | Prisma.BoxStyleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BoxStyle update
 */
export type BoxStyleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * The data needed to update a BoxStyle.
   */
  data: Prisma.XOR<Prisma.BoxStyleUpdateInput, Prisma.BoxStyleUncheckedUpdateInput>
  /**
   * Choose, which BoxStyle to update.
   */
  where: Prisma.BoxStyleWhereUniqueInput
}

/**
 * BoxStyle updateMany
 */
export type BoxStyleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BoxStyles.
   */
  data: Prisma.XOR<Prisma.BoxStyleUpdateManyMutationInput, Prisma.BoxStyleUncheckedUpdateManyInput>
  /**
   * Filter which BoxStyles to update
   */
  where?: Prisma.BoxStyleWhereInput
  /**
   * Limit how many BoxStyles to update.
   */
  limit?: number
}

/**
 * BoxStyle updateManyAndReturn
 */
export type BoxStyleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * The data used to update BoxStyles.
   */
  data: Prisma.XOR<Prisma.BoxStyleUpdateManyMutationInput, Prisma.BoxStyleUncheckedUpdateManyInput>
  /**
   * Filter which BoxStyles to update
   */
  where?: Prisma.BoxStyleWhereInput
  /**
   * Limit how many BoxStyles to update.
   */
  limit?: number
}

/**
 * BoxStyle upsert
 */
export type BoxStyleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * The filter to search for the BoxStyle to update in case it exists.
   */
  where: Prisma.BoxStyleWhereUniqueInput
  /**
   * In case the BoxStyle found by the `where` argument doesn't exist, create a new BoxStyle with this data.
   */
  create: Prisma.XOR<Prisma.BoxStyleCreateInput, Prisma.BoxStyleUncheckedCreateInput>
  /**
   * In case the BoxStyle was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BoxStyleUpdateInput, Prisma.BoxStyleUncheckedUpdateInput>
}

/**
 * BoxStyle delete
 */
export type BoxStyleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
  /**
   * Filter which BoxStyle to delete.
   */
  where: Prisma.BoxStyleWhereUniqueInput
}

/**
 * BoxStyle deleteMany
 */
export type BoxStyleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BoxStyles to delete
   */
  where?: Prisma.BoxStyleWhereInput
  /**
   * Limit how many BoxStyles to delete.
   */
  limit?: number
}

/**
 * BoxStyle.products
 */
export type BoxStyle$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * BoxStyle without action
 */
export type BoxStyleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BoxStyle
   */
  select?: Prisma.BoxStyleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BoxStyle
   */
  omit?: Prisma.BoxStyleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BoxStyleInclude<ExtArgs> | null
}
