
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Finish` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Finish
 * 
 */
export type FinishModel = runtime.Types.Result.DefaultSelection<Prisma.$FinishPayload>

export type AggregateFinish = {
  _count: FinishCountAggregateOutputType | null
  _min: FinishMinAggregateOutputType | null
  _max: FinishMaxAggregateOutputType | null
}

export type FinishMinAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FinishMaxAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FinishCountAggregateOutputType = {
  id: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FinishMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type FinishMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type FinishCountAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FinishAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Finish to aggregate.
   */
  where?: Prisma.FinishWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Finishes to fetch.
   */
  orderBy?: Prisma.FinishOrderByWithRelationInput | Prisma.FinishOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FinishWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Finishes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Finishes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Finishes
  **/
  _count?: true | FinishCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FinishMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FinishMaxAggregateInputType
}

export type GetFinishAggregateType<T extends FinishAggregateArgs> = {
      [P in keyof T & keyof AggregateFinish]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFinish[P]>
    : Prisma.GetScalarType<T[P], AggregateFinish[P]>
}




export type FinishGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FinishWhereInput
  orderBy?: Prisma.FinishOrderByWithAggregationInput | Prisma.FinishOrderByWithAggregationInput[]
  by: Prisma.FinishScalarFieldEnum[] | Prisma.FinishScalarFieldEnum
  having?: Prisma.FinishScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FinishCountAggregateInputType | true
  _min?: FinishMinAggregateInputType
  _max?: FinishMaxAggregateInputType
}

export type FinishGroupByOutputType = {
  id: string
  name: string
  createdAt: Date
  updatedAt: Date
  _count: FinishCountAggregateOutputType | null
  _min: FinishMinAggregateOutputType | null
  _max: FinishMaxAggregateOutputType | null
}

type GetFinishGroupByPayload<T extends FinishGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FinishGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FinishGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FinishGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FinishGroupByOutputType[P]>
      }
    >
  >



export type FinishWhereInput = {
  AND?: Prisma.FinishWhereInput | Prisma.FinishWhereInput[]
  OR?: Prisma.FinishWhereInput[]
  NOT?: Prisma.FinishWhereInput | Prisma.FinishWhereInput[]
  id?: Prisma.UuidFilter<"Finish"> | string
  name?: Prisma.StringFilter<"Finish"> | string
  createdAt?: Prisma.DateTimeFilter<"Finish"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Finish"> | Date | string
  products?: Prisma.ProductListRelationFilter
}

export type FinishOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  products?: Prisma.ProductOrderByRelationAggregateInput
}

export type FinishWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.FinishWhereInput | Prisma.FinishWhereInput[]
  OR?: Prisma.FinishWhereInput[]
  NOT?: Prisma.FinishWhereInput | Prisma.FinishWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Finish"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Finish"> | Date | string
  products?: Prisma.ProductListRelationFilter
}, "id" | "name">

export type FinishOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FinishCountOrderByAggregateInput
  _max?: Prisma.FinishMaxOrderByAggregateInput
  _min?: Prisma.FinishMinOrderByAggregateInput
}

export type FinishScalarWhereWithAggregatesInput = {
  AND?: Prisma.FinishScalarWhereWithAggregatesInput | Prisma.FinishScalarWhereWithAggregatesInput[]
  OR?: Prisma.FinishScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FinishScalarWhereWithAggregatesInput | Prisma.FinishScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Finish"> | string
  name?: Prisma.StringWithAggregatesFilter<"Finish"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Finish"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Finish"> | Date | string
}

export type FinishCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutFinishInput
}

export type FinishUncheckedCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutFinishInput
}

export type FinishUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutFinishNestedInput
}

export type FinishUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUncheckedUpdateManyWithoutFinishNestedInput
}

export type FinishCreateManyInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FinishUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FinishUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FinishCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FinishMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FinishMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FinishScalarRelationFilter = {
  is?: Prisma.FinishWhereInput
  isNot?: Prisma.FinishWhereInput
}

export type FinishCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.FinishCreateWithoutProductsInput, Prisma.FinishUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.FinishCreateOrConnectWithoutProductsInput
  connect?: Prisma.FinishWhereUniqueInput
}

export type FinishUpdateOneRequiredWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.FinishCreateWithoutProductsInput, Prisma.FinishUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.FinishCreateOrConnectWithoutProductsInput
  upsert?: Prisma.FinishUpsertWithoutProductsInput
  connect?: Prisma.FinishWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FinishUpdateToOneWithWhereWithoutProductsInput, Prisma.FinishUpdateWithoutProductsInput>, Prisma.FinishUncheckedUpdateWithoutProductsInput>
}

export type FinishCreateWithoutProductsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FinishUncheckedCreateWithoutProductsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FinishCreateOrConnectWithoutProductsInput = {
  where: Prisma.FinishWhereUniqueInput
  create: Prisma.XOR<Prisma.FinishCreateWithoutProductsInput, Prisma.FinishUncheckedCreateWithoutProductsInput>
}

export type FinishUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.FinishUpdateWithoutProductsInput, Prisma.FinishUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.FinishCreateWithoutProductsInput, Prisma.FinishUncheckedCreateWithoutProductsInput>
  where?: Prisma.FinishWhereInput
}

export type FinishUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.FinishWhereInput
  data: Prisma.XOR<Prisma.FinishUpdateWithoutProductsInput, Prisma.FinishUncheckedUpdateWithoutProductsInput>
}

export type FinishUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FinishUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FinishCountOutputType
 */

export type FinishCountOutputType = {
  products: number
}

export type FinishCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | FinishCountOutputTypeCountProductsArgs
}

/**
 * FinishCountOutputType without action
 */
export type FinishCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinishCountOutputType
   */
  select?: Prisma.FinishCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FinishCountOutputType without action
 */
export type FinishCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}


export type FinishSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  products?: boolean | Prisma.Finish$productsArgs<ExtArgs>
  _count?: boolean | Prisma.FinishCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["finish"]>

export type FinishSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["finish"]>

export type FinishSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["finish"]>

export type FinishSelectScalar = {
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FinishOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["finish"]>
export type FinishInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | Prisma.Finish$productsArgs<ExtArgs>
  _count?: boolean | Prisma.FinishCountOutputTypeDefaultArgs<ExtArgs>
}
export type FinishIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FinishIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FinishPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Finish"
  objects: {
    products: Prisma.$ProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["finish"]>
  composites: {}
}

export type FinishGetPayload<S extends boolean | null | undefined | FinishDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FinishPayload, S>

export type FinishCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FinishFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FinishCountAggregateInputType | true
  }

export interface FinishDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Finish'], meta: { name: 'Finish' } }
  /**
   * Find zero or one Finish that matches the filter.
   * @param {FinishFindUniqueArgs} args - Arguments to find a Finish
   * @example
   * // Get one Finish
   * const finish = await prisma.finish.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FinishFindUniqueArgs>(args: Prisma.SelectSubset<T, FinishFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FinishClient<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Finish that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FinishFindUniqueOrThrowArgs} args - Arguments to find a Finish
   * @example
   * // Get one Finish
   * const finish = await prisma.finish.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FinishFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FinishFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FinishClient<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Finish that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinishFindFirstArgs} args - Arguments to find a Finish
   * @example
   * // Get one Finish
   * const finish = await prisma.finish.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FinishFindFirstArgs>(args?: Prisma.SelectSubset<T, FinishFindFirstArgs<ExtArgs>>): Prisma.Prisma__FinishClient<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Finish that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinishFindFirstOrThrowArgs} args - Arguments to find a Finish
   * @example
   * // Get one Finish
   * const finish = await prisma.finish.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FinishFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FinishFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FinishClient<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Finishes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinishFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Finishes
   * const finishes = await prisma.finish.findMany()
   * 
   * // Get first 10 Finishes
   * const finishes = await prisma.finish.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const finishWithIdOnly = await prisma.finish.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FinishFindManyArgs>(args?: Prisma.SelectSubset<T, FinishFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Finish.
   * @param {FinishCreateArgs} args - Arguments to create a Finish.
   * @example
   * // Create one Finish
   * const Finish = await prisma.finish.create({
   *   data: {
   *     // ... data to create a Finish
   *   }
   * })
   * 
   */
  create<T extends FinishCreateArgs>(args: Prisma.SelectSubset<T, FinishCreateArgs<ExtArgs>>): Prisma.Prisma__FinishClient<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Finishes.
   * @param {FinishCreateManyArgs} args - Arguments to create many Finishes.
   * @example
   * // Create many Finishes
   * const finish = await prisma.finish.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FinishCreateManyArgs>(args?: Prisma.SelectSubset<T, FinishCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Finishes and returns the data saved in the database.
   * @param {FinishCreateManyAndReturnArgs} args - Arguments to create many Finishes.
   * @example
   * // Create many Finishes
   * const finish = await prisma.finish.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Finishes and only return the `id`
   * const finishWithIdOnly = await prisma.finish.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FinishCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FinishCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Finish.
   * @param {FinishDeleteArgs} args - Arguments to delete one Finish.
   * @example
   * // Delete one Finish
   * const Finish = await prisma.finish.delete({
   *   where: {
   *     // ... filter to delete one Finish
   *   }
   * })
   * 
   */
  delete<T extends FinishDeleteArgs>(args: Prisma.SelectSubset<T, FinishDeleteArgs<ExtArgs>>): Prisma.Prisma__FinishClient<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Finish.
   * @param {FinishUpdateArgs} args - Arguments to update one Finish.
   * @example
   * // Update one Finish
   * const finish = await prisma.finish.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FinishUpdateArgs>(args: Prisma.SelectSubset<T, FinishUpdateArgs<ExtArgs>>): Prisma.Prisma__FinishClient<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Finishes.
   * @param {FinishDeleteManyArgs} args - Arguments to filter Finishes to delete.
   * @example
   * // Delete a few Finishes
   * const { count } = await prisma.finish.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FinishDeleteManyArgs>(args?: Prisma.SelectSubset<T, FinishDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Finishes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinishUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Finishes
   * const finish = await prisma.finish.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FinishUpdateManyArgs>(args: Prisma.SelectSubset<T, FinishUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Finishes and returns the data updated in the database.
   * @param {FinishUpdateManyAndReturnArgs} args - Arguments to update many Finishes.
   * @example
   * // Update many Finishes
   * const finish = await prisma.finish.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Finishes and only return the `id`
   * const finishWithIdOnly = await prisma.finish.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FinishUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FinishUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Finish.
   * @param {FinishUpsertArgs} args - Arguments to update or create a Finish.
   * @example
   * // Update or create a Finish
   * const finish = await prisma.finish.upsert({
   *   create: {
   *     // ... data to create a Finish
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Finish we want to update
   *   }
   * })
   */
  upsert<T extends FinishUpsertArgs>(args: Prisma.SelectSubset<T, FinishUpsertArgs<ExtArgs>>): Prisma.Prisma__FinishClient<runtime.Types.Result.GetResult<Prisma.$FinishPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Finishes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinishCountArgs} args - Arguments to filter Finishes to count.
   * @example
   * // Count the number of Finishes
   * const count = await prisma.finish.count({
   *   where: {
   *     // ... the filter for the Finishes we want to count
   *   }
   * })
  **/
  count<T extends FinishCountArgs>(
    args?: Prisma.Subset<T, FinishCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FinishCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Finish.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinishAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FinishAggregateArgs>(args: Prisma.Subset<T, FinishAggregateArgs>): Prisma.PrismaPromise<GetFinishAggregateType<T>>

  /**
   * Group by Finish.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinishGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FinishGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FinishGroupByArgs['orderBy'] }
      : { orderBy?: FinishGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FinishGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFinishGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Finish model
 */
readonly fields: FinishFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Finish.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FinishClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  products<T extends Prisma.Finish$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Finish$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Finish model
 */
export interface FinishFieldRefs {
  readonly id: Prisma.FieldRef<"Finish", 'String'>
  readonly name: Prisma.FieldRef<"Finish", 'String'>
  readonly createdAt: Prisma.FieldRef<"Finish", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Finish", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Finish findUnique
 */
export type FinishFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * Filter, which Finish to fetch.
   */
  where: Prisma.FinishWhereUniqueInput
}

/**
 * Finish findUniqueOrThrow
 */
export type FinishFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * Filter, which Finish to fetch.
   */
  where: Prisma.FinishWhereUniqueInput
}

/**
 * Finish findFirst
 */
export type FinishFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * Filter, which Finish to fetch.
   */
  where?: Prisma.FinishWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Finishes to fetch.
   */
  orderBy?: Prisma.FinishOrderByWithRelationInput | Prisma.FinishOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Finishes.
   */
  cursor?: Prisma.FinishWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Finishes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Finishes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Finishes.
   */
  distinct?: Prisma.FinishScalarFieldEnum | Prisma.FinishScalarFieldEnum[]
}

/**
 * Finish findFirstOrThrow
 */
export type FinishFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * Filter, which Finish to fetch.
   */
  where?: Prisma.FinishWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Finishes to fetch.
   */
  orderBy?: Prisma.FinishOrderByWithRelationInput | Prisma.FinishOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Finishes.
   */
  cursor?: Prisma.FinishWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Finishes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Finishes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Finishes.
   */
  distinct?: Prisma.FinishScalarFieldEnum | Prisma.FinishScalarFieldEnum[]
}

/**
 * Finish findMany
 */
export type FinishFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * Filter, which Finishes to fetch.
   */
  where?: Prisma.FinishWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Finishes to fetch.
   */
  orderBy?: Prisma.FinishOrderByWithRelationInput | Prisma.FinishOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Finishes.
   */
  cursor?: Prisma.FinishWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Finishes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Finishes.
   */
  skip?: number
  distinct?: Prisma.FinishScalarFieldEnum | Prisma.FinishScalarFieldEnum[]
}

/**
 * Finish create
 */
export type FinishCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * The data needed to create a Finish.
   */
  data: Prisma.XOR<Prisma.FinishCreateInput, Prisma.FinishUncheckedCreateInput>
}

/**
 * Finish createMany
 */
export type FinishCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Finishes.
   */
  data: Prisma.FinishCreateManyInput | Prisma.FinishCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Finish createManyAndReturn
 */
export type FinishCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * The data used to create many Finishes.
   */
  data: Prisma.FinishCreateManyInput | Prisma.FinishCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Finish update
 */
export type FinishUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * The data needed to update a Finish.
   */
  data: Prisma.XOR<Prisma.FinishUpdateInput, Prisma.FinishUncheckedUpdateInput>
  /**
   * Choose, which Finish to update.
   */
  where: Prisma.FinishWhereUniqueInput
}

/**
 * Finish updateMany
 */
export type FinishUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Finishes.
   */
  data: Prisma.XOR<Prisma.FinishUpdateManyMutationInput, Prisma.FinishUncheckedUpdateManyInput>
  /**
   * Filter which Finishes to update
   */
  where?: Prisma.FinishWhereInput
  /**
   * Limit how many Finishes to update.
   */
  limit?: number
}

/**
 * Finish updateManyAndReturn
 */
export type FinishUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * The data used to update Finishes.
   */
  data: Prisma.XOR<Prisma.FinishUpdateManyMutationInput, Prisma.FinishUncheckedUpdateManyInput>
  /**
   * Filter which Finishes to update
   */
  where?: Prisma.FinishWhereInput
  /**
   * Limit how many Finishes to update.
   */
  limit?: number
}

/**
 * Finish upsert
 */
export type FinishUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * The filter to search for the Finish to update in case it exists.
   */
  where: Prisma.FinishWhereUniqueInput
  /**
   * In case the Finish found by the `where` argument doesn't exist, create a new Finish with this data.
   */
  create: Prisma.XOR<Prisma.FinishCreateInput, Prisma.FinishUncheckedCreateInput>
  /**
   * In case the Finish was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FinishUpdateInput, Prisma.FinishUncheckedUpdateInput>
}

/**
 * Finish delete
 */
export type FinishDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
  /**
   * Filter which Finish to delete.
   */
  where: Prisma.FinishWhereUniqueInput
}

/**
 * Finish deleteMany
 */
export type FinishDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Finishes to delete
   */
  where?: Prisma.FinishWhereInput
  /**
   * Limit how many Finishes to delete.
   */
  limit?: number
}

/**
 * Finish.products
 */
export type Finish$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Finish without action
 */
export type FinishDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Finish
   */
  select?: Prisma.FinishSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Finish
   */
  omit?: Prisma.FinishOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinishInclude<ExtArgs> | null
}
