
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Material` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Material
 * 
 */
export type MaterialModel = runtime.Types.Result.DefaultSelection<Prisma.$MaterialPayload>

export type AggregateMaterial = {
  _count: MaterialCountAggregateOutputType | null
  _min: MaterialMinAggregateOutputType | null
  _max: MaterialMaxAggregateOutputType | null
}

export type MaterialMinAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MaterialMaxAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MaterialCountAggregateOutputType = {
  id: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MaterialMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type MaterialMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type MaterialCountAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MaterialAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Material to aggregate.
   */
  where?: Prisma.MaterialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Materials to fetch.
   */
  orderBy?: Prisma.MaterialOrderByWithRelationInput | Prisma.MaterialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MaterialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Materials
  **/
  _count?: true | MaterialCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaterialMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaterialMaxAggregateInputType
}

export type GetMaterialAggregateType<T extends MaterialAggregateArgs> = {
      [P in keyof T & keyof AggregateMaterial]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaterial[P]>
    : Prisma.GetScalarType<T[P], AggregateMaterial[P]>
}




export type MaterialGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaterialWhereInput
  orderBy?: Prisma.MaterialOrderByWithAggregationInput | Prisma.MaterialOrderByWithAggregationInput[]
  by: Prisma.MaterialScalarFieldEnum[] | Prisma.MaterialScalarFieldEnum
  having?: Prisma.MaterialScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaterialCountAggregateInputType | true
  _min?: MaterialMinAggregateInputType
  _max?: MaterialMaxAggregateInputType
}

export type MaterialGroupByOutputType = {
  id: string
  name: string
  createdAt: Date
  updatedAt: Date
  _count: MaterialCountAggregateOutputType | null
  _min: MaterialMinAggregateOutputType | null
  _max: MaterialMaxAggregateOutputType | null
}

type GetMaterialGroupByPayload<T extends MaterialGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaterialGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaterialGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaterialGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaterialGroupByOutputType[P]>
      }
    >
  >



export type MaterialWhereInput = {
  AND?: Prisma.MaterialWhereInput | Prisma.MaterialWhereInput[]
  OR?: Prisma.MaterialWhereInput[]
  NOT?: Prisma.MaterialWhereInput | Prisma.MaterialWhereInput[]
  id?: Prisma.UuidFilter<"Material"> | string
  name?: Prisma.StringFilter<"Material"> | string
  createdAt?: Prisma.DateTimeFilter<"Material"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Material"> | Date | string
  products?: Prisma.ProductListRelationFilter
}

export type MaterialOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  products?: Prisma.ProductOrderByRelationAggregateInput
}

export type MaterialWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.MaterialWhereInput | Prisma.MaterialWhereInput[]
  OR?: Prisma.MaterialWhereInput[]
  NOT?: Prisma.MaterialWhereInput | Prisma.MaterialWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Material"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Material"> | Date | string
  products?: Prisma.ProductListRelationFilter
}, "id" | "name">

export type MaterialOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MaterialCountOrderByAggregateInput
  _max?: Prisma.MaterialMaxOrderByAggregateInput
  _min?: Prisma.MaterialMinOrderByAggregateInput
}

export type MaterialScalarWhereWithAggregatesInput = {
  AND?: Prisma.MaterialScalarWhereWithAggregatesInput | Prisma.MaterialScalarWhereWithAggregatesInput[]
  OR?: Prisma.MaterialScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MaterialScalarWhereWithAggregatesInput | Prisma.MaterialScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Material"> | string
  name?: Prisma.StringWithAggregatesFilter<"Material"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Material"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Material"> | Date | string
}

export type MaterialCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutMaterialInput
}

export type MaterialUncheckedCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutMaterialInput
}

export type MaterialUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutMaterialNestedInput
}

export type MaterialUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUncheckedUpdateManyWithoutMaterialNestedInput
}

export type MaterialCreateManyInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MaterialUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaterialMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaterialMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MaterialScalarRelationFilter = {
  is?: Prisma.MaterialWhereInput
  isNot?: Prisma.MaterialWhereInput
}

export type MaterialCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.MaterialCreateWithoutProductsInput, Prisma.MaterialUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.MaterialCreateOrConnectWithoutProductsInput
  connect?: Prisma.MaterialWhereUniqueInput
}

export type MaterialUpdateOneRequiredWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.MaterialCreateWithoutProductsInput, Prisma.MaterialUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.MaterialCreateOrConnectWithoutProductsInput
  upsert?: Prisma.MaterialUpsertWithoutProductsInput
  connect?: Prisma.MaterialWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MaterialUpdateToOneWithWhereWithoutProductsInput, Prisma.MaterialUpdateWithoutProductsInput>, Prisma.MaterialUncheckedUpdateWithoutProductsInput>
}

export type MaterialCreateWithoutProductsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MaterialUncheckedCreateWithoutProductsInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MaterialCreateOrConnectWithoutProductsInput = {
  where: Prisma.MaterialWhereUniqueInput
  create: Prisma.XOR<Prisma.MaterialCreateWithoutProductsInput, Prisma.MaterialUncheckedCreateWithoutProductsInput>
}

export type MaterialUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.MaterialUpdateWithoutProductsInput, Prisma.MaterialUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.MaterialCreateWithoutProductsInput, Prisma.MaterialUncheckedCreateWithoutProductsInput>
  where?: Prisma.MaterialWhereInput
}

export type MaterialUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.MaterialWhereInput
  data: Prisma.XOR<Prisma.MaterialUpdateWithoutProductsInput, Prisma.MaterialUncheckedUpdateWithoutProductsInput>
}

export type MaterialUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaterialUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MaterialCountOutputType
 */

export type MaterialCountOutputType = {
  products: number
}

export type MaterialCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | MaterialCountOutputTypeCountProductsArgs
}

/**
 * MaterialCountOutputType without action
 */
export type MaterialCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialCountOutputType
   */
  select?: Prisma.MaterialCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MaterialCountOutputType without action
 */
export type MaterialCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}


export type MaterialSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  products?: boolean | Prisma.Material$productsArgs<ExtArgs>
  _count?: boolean | Prisma.MaterialCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["material"]>

export type MaterialSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["material"]>

export type MaterialSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["material"]>

export type MaterialSelectScalar = {
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MaterialOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["material"]>
export type MaterialInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | Prisma.Material$productsArgs<ExtArgs>
  _count?: boolean | Prisma.MaterialCountOutputTypeDefaultArgs<ExtArgs>
}
export type MaterialIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MaterialIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MaterialPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Material"
  objects: {
    products: Prisma.$ProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["material"]>
  composites: {}
}

export type MaterialGetPayload<S extends boolean | null | undefined | MaterialDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MaterialPayload, S>

export type MaterialCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MaterialFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaterialCountAggregateInputType | true
  }

export interface MaterialDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Material'], meta: { name: 'Material' } }
  /**
   * Find zero or one Material that matches the filter.
   * @param {MaterialFindUniqueArgs} args - Arguments to find a Material
   * @example
   * // Get one Material
   * const material = await prisma.material.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MaterialFindUniqueArgs>(args: Prisma.SelectSubset<T, MaterialFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Material that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MaterialFindUniqueOrThrowArgs} args - Arguments to find a Material
   * @example
   * // Get one Material
   * const material = await prisma.material.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MaterialFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MaterialFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Material that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialFindFirstArgs} args - Arguments to find a Material
   * @example
   * // Get one Material
   * const material = await prisma.material.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MaterialFindFirstArgs>(args?: Prisma.SelectSubset<T, MaterialFindFirstArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Material that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialFindFirstOrThrowArgs} args - Arguments to find a Material
   * @example
   * // Get one Material
   * const material = await prisma.material.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MaterialFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MaterialFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Materials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Materials
   * const materials = await prisma.material.findMany()
   * 
   * // Get first 10 Materials
   * const materials = await prisma.material.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const materialWithIdOnly = await prisma.material.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MaterialFindManyArgs>(args?: Prisma.SelectSubset<T, MaterialFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Material.
   * @param {MaterialCreateArgs} args - Arguments to create a Material.
   * @example
   * // Create one Material
   * const Material = await prisma.material.create({
   *   data: {
   *     // ... data to create a Material
   *   }
   * })
   * 
   */
  create<T extends MaterialCreateArgs>(args: Prisma.SelectSubset<T, MaterialCreateArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Materials.
   * @param {MaterialCreateManyArgs} args - Arguments to create many Materials.
   * @example
   * // Create many Materials
   * const material = await prisma.material.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MaterialCreateManyArgs>(args?: Prisma.SelectSubset<T, MaterialCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Materials and returns the data saved in the database.
   * @param {MaterialCreateManyAndReturnArgs} args - Arguments to create many Materials.
   * @example
   * // Create many Materials
   * const material = await prisma.material.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Materials and only return the `id`
   * const materialWithIdOnly = await prisma.material.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MaterialCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MaterialCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Material.
   * @param {MaterialDeleteArgs} args - Arguments to delete one Material.
   * @example
   * // Delete one Material
   * const Material = await prisma.material.delete({
   *   where: {
   *     // ... filter to delete one Material
   *   }
   * })
   * 
   */
  delete<T extends MaterialDeleteArgs>(args: Prisma.SelectSubset<T, MaterialDeleteArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Material.
   * @param {MaterialUpdateArgs} args - Arguments to update one Material.
   * @example
   * // Update one Material
   * const material = await prisma.material.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MaterialUpdateArgs>(args: Prisma.SelectSubset<T, MaterialUpdateArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Materials.
   * @param {MaterialDeleteManyArgs} args - Arguments to filter Materials to delete.
   * @example
   * // Delete a few Materials
   * const { count } = await prisma.material.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MaterialDeleteManyArgs>(args?: Prisma.SelectSubset<T, MaterialDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Materials
   * const material = await prisma.material.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MaterialUpdateManyArgs>(args: Prisma.SelectSubset<T, MaterialUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Materials and returns the data updated in the database.
   * @param {MaterialUpdateManyAndReturnArgs} args - Arguments to update many Materials.
   * @example
   * // Update many Materials
   * const material = await prisma.material.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Materials and only return the `id`
   * const materialWithIdOnly = await prisma.material.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MaterialUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MaterialUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Material.
   * @param {MaterialUpsertArgs} args - Arguments to update or create a Material.
   * @example
   * // Update or create a Material
   * const material = await prisma.material.upsert({
   *   create: {
   *     // ... data to create a Material
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Material we want to update
   *   }
   * })
   */
  upsert<T extends MaterialUpsertArgs>(args: Prisma.SelectSubset<T, MaterialUpsertArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialCountArgs} args - Arguments to filter Materials to count.
   * @example
   * // Count the number of Materials
   * const count = await prisma.material.count({
   *   where: {
   *     // ... the filter for the Materials we want to count
   *   }
   * })
  **/
  count<T extends MaterialCountArgs>(
    args?: Prisma.Subset<T, MaterialCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaterialCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Material.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaterialAggregateArgs>(args: Prisma.Subset<T, MaterialAggregateArgs>): Prisma.PrismaPromise<GetMaterialAggregateType<T>>

  /**
   * Group by Material.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MaterialGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MaterialGroupByArgs['orderBy'] }
      : { orderBy?: MaterialGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MaterialGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaterialGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Material model
 */
readonly fields: MaterialFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Material.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MaterialClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  products<T extends Prisma.Material$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Material$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Material model
 */
export interface MaterialFieldRefs {
  readonly id: Prisma.FieldRef<"Material", 'String'>
  readonly name: Prisma.FieldRef<"Material", 'String'>
  readonly createdAt: Prisma.FieldRef<"Material", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Material", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Material findUnique
 */
export type MaterialFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * Filter, which Material to fetch.
   */
  where: Prisma.MaterialWhereUniqueInput
}

/**
 * Material findUniqueOrThrow
 */
export type MaterialFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * Filter, which Material to fetch.
   */
  where: Prisma.MaterialWhereUniqueInput
}

/**
 * Material findFirst
 */
export type MaterialFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * Filter, which Material to fetch.
   */
  where?: Prisma.MaterialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Materials to fetch.
   */
  orderBy?: Prisma.MaterialOrderByWithRelationInput | Prisma.MaterialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Materials.
   */
  cursor?: Prisma.MaterialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Materials.
   */
  distinct?: Prisma.MaterialScalarFieldEnum | Prisma.MaterialScalarFieldEnum[]
}

/**
 * Material findFirstOrThrow
 */
export type MaterialFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * Filter, which Material to fetch.
   */
  where?: Prisma.MaterialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Materials to fetch.
   */
  orderBy?: Prisma.MaterialOrderByWithRelationInput | Prisma.MaterialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Materials.
   */
  cursor?: Prisma.MaterialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Materials.
   */
  distinct?: Prisma.MaterialScalarFieldEnum | Prisma.MaterialScalarFieldEnum[]
}

/**
 * Material findMany
 */
export type MaterialFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * Filter, which Materials to fetch.
   */
  where?: Prisma.MaterialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Materials to fetch.
   */
  orderBy?: Prisma.MaterialOrderByWithRelationInput | Prisma.MaterialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Materials.
   */
  cursor?: Prisma.MaterialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Materials.
   */
  skip?: number
  distinct?: Prisma.MaterialScalarFieldEnum | Prisma.MaterialScalarFieldEnum[]
}

/**
 * Material create
 */
export type MaterialCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * The data needed to create a Material.
   */
  data: Prisma.XOR<Prisma.MaterialCreateInput, Prisma.MaterialUncheckedCreateInput>
}

/**
 * Material createMany
 */
export type MaterialCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Materials.
   */
  data: Prisma.MaterialCreateManyInput | Prisma.MaterialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Material createManyAndReturn
 */
export type MaterialCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * The data used to create many Materials.
   */
  data: Prisma.MaterialCreateManyInput | Prisma.MaterialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Material update
 */
export type MaterialUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * The data needed to update a Material.
   */
  data: Prisma.XOR<Prisma.MaterialUpdateInput, Prisma.MaterialUncheckedUpdateInput>
  /**
   * Choose, which Material to update.
   */
  where: Prisma.MaterialWhereUniqueInput
}

/**
 * Material updateMany
 */
export type MaterialUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Materials.
   */
  data: Prisma.XOR<Prisma.MaterialUpdateManyMutationInput, Prisma.MaterialUncheckedUpdateManyInput>
  /**
   * Filter which Materials to update
   */
  where?: Prisma.MaterialWhereInput
  /**
   * Limit how many Materials to update.
   */
  limit?: number
}

/**
 * Material updateManyAndReturn
 */
export type MaterialUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * The data used to update Materials.
   */
  data: Prisma.XOR<Prisma.MaterialUpdateManyMutationInput, Prisma.MaterialUncheckedUpdateManyInput>
  /**
   * Filter which Materials to update
   */
  where?: Prisma.MaterialWhereInput
  /**
   * Limit how many Materials to update.
   */
  limit?: number
}

/**
 * Material upsert
 */
export type MaterialUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * The filter to search for the Material to update in case it exists.
   */
  where: Prisma.MaterialWhereUniqueInput
  /**
   * In case the Material found by the `where` argument doesn't exist, create a new Material with this data.
   */
  create: Prisma.XOR<Prisma.MaterialCreateInput, Prisma.MaterialUncheckedCreateInput>
  /**
   * In case the Material was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MaterialUpdateInput, Prisma.MaterialUncheckedUpdateInput>
}

/**
 * Material delete
 */
export type MaterialDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
  /**
   * Filter which Material to delete.
   */
  where: Prisma.MaterialWhereUniqueInput
}

/**
 * Material deleteMany
 */
export type MaterialDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Materials to delete
   */
  where?: Prisma.MaterialWhereInput
  /**
   * Limit how many Materials to delete.
   */
  limit?: number
}

/**
 * Material.products
 */
export type Material$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Material without action
 */
export type MaterialDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Material
   */
  select?: Prisma.MaterialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Material
   */
  omit?: Prisma.MaterialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialInclude<ExtArgs> | null
}
