
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `QuoteRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model QuoteRequest
 * 
 */
export type QuoteRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$QuoteRequestPayload>

export type AggregateQuoteRequest = {
  _count: QuoteRequestCountAggregateOutputType | null
  _min: QuoteRequestMinAggregateOutputType | null
  _max: QuoteRequestMaxAggregateOutputType | null
}

export type QuoteRequestMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phone: string | null
  message: string | null
  productId: string | null
  createdAt: Date | null
}

export type QuoteRequestMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phone: string | null
  message: string | null
  productId: string | null
  createdAt: Date | null
}

export type QuoteRequestCountAggregateOutputType = {
  id: number
  name: number
  email: number
  phone: number
  message: number
  productId: number
  createdAt: number
  _all: number
}


export type QuoteRequestMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  message?: true
  productId?: true
  createdAt?: true
}

export type QuoteRequestMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  message?: true
  productId?: true
  createdAt?: true
}

export type QuoteRequestCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  message?: true
  productId?: true
  createdAt?: true
  _all?: true
}

export type QuoteRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuoteRequest to aggregate.
   */
  where?: Prisma.QuoteRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuoteRequests to fetch.
   */
  orderBy?: Prisma.QuoteRequestOrderByWithRelationInput | Prisma.QuoteRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuoteRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuoteRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuoteRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuoteRequests
  **/
  _count?: true | QuoteRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuoteRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuoteRequestMaxAggregateInputType
}

export type GetQuoteRequestAggregateType<T extends QuoteRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateQuoteRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuoteRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateQuoteRequest[P]>
}




export type QuoteRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuoteRequestWhereInput
  orderBy?: Prisma.QuoteRequestOrderByWithAggregationInput | Prisma.QuoteRequestOrderByWithAggregationInput[]
  by: Prisma.QuoteRequestScalarFieldEnum[] | Prisma.QuoteRequestScalarFieldEnum
  having?: Prisma.QuoteRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuoteRequestCountAggregateInputType | true
  _min?: QuoteRequestMinAggregateInputType
  _max?: QuoteRequestMaxAggregateInputType
}

export type QuoteRequestGroupByOutputType = {
  id: string
  name: string
  email: string
  phone: string
  message: string
  productId: string | null
  createdAt: Date
  _count: QuoteRequestCountAggregateOutputType | null
  _min: QuoteRequestMinAggregateOutputType | null
  _max: QuoteRequestMaxAggregateOutputType | null
}

type GetQuoteRequestGroupByPayload<T extends QuoteRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuoteRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuoteRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuoteRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuoteRequestGroupByOutputType[P]>
      }
    >
  >



export type QuoteRequestWhereInput = {
  AND?: Prisma.QuoteRequestWhereInput | Prisma.QuoteRequestWhereInput[]
  OR?: Prisma.QuoteRequestWhereInput[]
  NOT?: Prisma.QuoteRequestWhereInput | Prisma.QuoteRequestWhereInput[]
  id?: Prisma.UuidFilter<"QuoteRequest"> | string
  name?: Prisma.StringFilter<"QuoteRequest"> | string
  email?: Prisma.StringFilter<"QuoteRequest"> | string
  phone?: Prisma.StringFilter<"QuoteRequest"> | string
  message?: Prisma.StringFilter<"QuoteRequest"> | string
  productId?: Prisma.UuidNullableFilter<"QuoteRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"QuoteRequest"> | Date | string
  product?: Prisma.XOR<Prisma.ProductNullableScalarRelationFilter, Prisma.ProductWhereInput> | null
}

export type QuoteRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  productId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type QuoteRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.QuoteRequestWhereInput | Prisma.QuoteRequestWhereInput[]
  OR?: Prisma.QuoteRequestWhereInput[]
  NOT?: Prisma.QuoteRequestWhereInput | Prisma.QuoteRequestWhereInput[]
  name?: Prisma.StringFilter<"QuoteRequest"> | string
  email?: Prisma.StringFilter<"QuoteRequest"> | string
  phone?: Prisma.StringFilter<"QuoteRequest"> | string
  message?: Prisma.StringFilter<"QuoteRequest"> | string
  productId?: Prisma.UuidNullableFilter<"QuoteRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"QuoteRequest"> | Date | string
  product?: Prisma.XOR<Prisma.ProductNullableScalarRelationFilter, Prisma.ProductWhereInput> | null
}, "id">

export type QuoteRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  productId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.QuoteRequestCountOrderByAggregateInput
  _max?: Prisma.QuoteRequestMaxOrderByAggregateInput
  _min?: Prisma.QuoteRequestMinOrderByAggregateInput
}

export type QuoteRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuoteRequestScalarWhereWithAggregatesInput | Prisma.QuoteRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuoteRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuoteRequestScalarWhereWithAggregatesInput | Prisma.QuoteRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"QuoteRequest"> | string
  name?: Prisma.StringWithAggregatesFilter<"QuoteRequest"> | string
  email?: Prisma.StringWithAggregatesFilter<"QuoteRequest"> | string
  phone?: Prisma.StringWithAggregatesFilter<"QuoteRequest"> | string
  message?: Prisma.StringWithAggregatesFilter<"QuoteRequest"> | string
  productId?: Prisma.UuidNullableWithAggregatesFilter<"QuoteRequest"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuoteRequest"> | Date | string
}

export type QuoteRequestCreateInput = {
  id?: string
  name: string
  email: string
  phone: string
  message: string
  createdAt?: Date | string
  product?: Prisma.ProductCreateNestedOneWithoutQuotesInput
}

export type QuoteRequestUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  phone: string
  message: string
  productId?: string | null
  createdAt?: Date | string
}

export type QuoteRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneWithoutQuotesNestedInput
}

export type QuoteRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuoteRequestCreateManyInput = {
  id?: string
  name: string
  email: string
  phone: string
  message: string
  productId?: string | null
  createdAt?: Date | string
}

export type QuoteRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuoteRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuoteRequestListRelationFilter = {
  every?: Prisma.QuoteRequestWhereInput
  some?: Prisma.QuoteRequestWhereInput
  none?: Prisma.QuoteRequestWhereInput
}

export type QuoteRequestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuoteRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuoteRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuoteRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  message?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuoteRequestCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.QuoteRequestCreateWithoutProductInput, Prisma.QuoteRequestUncheckedCreateWithoutProductInput> | Prisma.QuoteRequestCreateWithoutProductInput[] | Prisma.QuoteRequestUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.QuoteRequestCreateOrConnectWithoutProductInput | Prisma.QuoteRequestCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.QuoteRequestCreateManyProductInputEnvelope
  connect?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
}

export type QuoteRequestUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.QuoteRequestCreateWithoutProductInput, Prisma.QuoteRequestUncheckedCreateWithoutProductInput> | Prisma.QuoteRequestCreateWithoutProductInput[] | Prisma.QuoteRequestUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.QuoteRequestCreateOrConnectWithoutProductInput | Prisma.QuoteRequestCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.QuoteRequestCreateManyProductInputEnvelope
  connect?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
}

export type QuoteRequestUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.QuoteRequestCreateWithoutProductInput, Prisma.QuoteRequestUncheckedCreateWithoutProductInput> | Prisma.QuoteRequestCreateWithoutProductInput[] | Prisma.QuoteRequestUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.QuoteRequestCreateOrConnectWithoutProductInput | Prisma.QuoteRequestCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.QuoteRequestUpsertWithWhereUniqueWithoutProductInput | Prisma.QuoteRequestUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.QuoteRequestCreateManyProductInputEnvelope
  set?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
  disconnect?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
  delete?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
  connect?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
  update?: Prisma.QuoteRequestUpdateWithWhereUniqueWithoutProductInput | Prisma.QuoteRequestUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.QuoteRequestUpdateManyWithWhereWithoutProductInput | Prisma.QuoteRequestUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.QuoteRequestScalarWhereInput | Prisma.QuoteRequestScalarWhereInput[]
}

export type QuoteRequestUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.QuoteRequestCreateWithoutProductInput, Prisma.QuoteRequestUncheckedCreateWithoutProductInput> | Prisma.QuoteRequestCreateWithoutProductInput[] | Prisma.QuoteRequestUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.QuoteRequestCreateOrConnectWithoutProductInput | Prisma.QuoteRequestCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.QuoteRequestUpsertWithWhereUniqueWithoutProductInput | Prisma.QuoteRequestUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.QuoteRequestCreateManyProductInputEnvelope
  set?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
  disconnect?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
  delete?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
  connect?: Prisma.QuoteRequestWhereUniqueInput | Prisma.QuoteRequestWhereUniqueInput[]
  update?: Prisma.QuoteRequestUpdateWithWhereUniqueWithoutProductInput | Prisma.QuoteRequestUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.QuoteRequestUpdateManyWithWhereWithoutProductInput | Prisma.QuoteRequestUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.QuoteRequestScalarWhereInput | Prisma.QuoteRequestScalarWhereInput[]
}

export type QuoteRequestCreateWithoutProductInput = {
  id?: string
  name: string
  email: string
  phone: string
  message: string
  createdAt?: Date | string
}

export type QuoteRequestUncheckedCreateWithoutProductInput = {
  id?: string
  name: string
  email: string
  phone: string
  message: string
  createdAt?: Date | string
}

export type QuoteRequestCreateOrConnectWithoutProductInput = {
  where: Prisma.QuoteRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.QuoteRequestCreateWithoutProductInput, Prisma.QuoteRequestUncheckedCreateWithoutProductInput>
}

export type QuoteRequestCreateManyProductInputEnvelope = {
  data: Prisma.QuoteRequestCreateManyProductInput | Prisma.QuoteRequestCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type QuoteRequestUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.QuoteRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.QuoteRequestUpdateWithoutProductInput, Prisma.QuoteRequestUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.QuoteRequestCreateWithoutProductInput, Prisma.QuoteRequestUncheckedCreateWithoutProductInput>
}

export type QuoteRequestUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.QuoteRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.QuoteRequestUpdateWithoutProductInput, Prisma.QuoteRequestUncheckedUpdateWithoutProductInput>
}

export type QuoteRequestUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.QuoteRequestScalarWhereInput
  data: Prisma.XOR<Prisma.QuoteRequestUpdateManyMutationInput, Prisma.QuoteRequestUncheckedUpdateManyWithoutProductInput>
}

export type QuoteRequestScalarWhereInput = {
  AND?: Prisma.QuoteRequestScalarWhereInput | Prisma.QuoteRequestScalarWhereInput[]
  OR?: Prisma.QuoteRequestScalarWhereInput[]
  NOT?: Prisma.QuoteRequestScalarWhereInput | Prisma.QuoteRequestScalarWhereInput[]
  id?: Prisma.UuidFilter<"QuoteRequest"> | string
  name?: Prisma.StringFilter<"QuoteRequest"> | string
  email?: Prisma.StringFilter<"QuoteRequest"> | string
  phone?: Prisma.StringFilter<"QuoteRequest"> | string
  message?: Prisma.StringFilter<"QuoteRequest"> | string
  productId?: Prisma.UuidNullableFilter<"QuoteRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"QuoteRequest"> | Date | string
}

export type QuoteRequestCreateManyProductInput = {
  id?: string
  name: string
  email: string
  phone: string
  message: string
  createdAt?: Date | string
}

export type QuoteRequestUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuoteRequestUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuoteRequestUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type QuoteRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  productId?: boolean
  createdAt?: boolean
  product?: boolean | Prisma.QuoteRequest$productArgs<ExtArgs>
}, ExtArgs["result"]["quoteRequest"]>

export type QuoteRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  productId?: boolean
  createdAt?: boolean
  product?: boolean | Prisma.QuoteRequest$productArgs<ExtArgs>
}, ExtArgs["result"]["quoteRequest"]>

export type QuoteRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  productId?: boolean
  createdAt?: boolean
  product?: boolean | Prisma.QuoteRequest$productArgs<ExtArgs>
}, ExtArgs["result"]["quoteRequest"]>

export type QuoteRequestSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  message?: boolean
  productId?: boolean
  createdAt?: boolean
}

export type QuoteRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "phone" | "message" | "productId" | "createdAt", ExtArgs["result"]["quoteRequest"]>
export type QuoteRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.QuoteRequest$productArgs<ExtArgs>
}
export type QuoteRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.QuoteRequest$productArgs<ExtArgs>
}
export type QuoteRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.QuoteRequest$productArgs<ExtArgs>
}

export type $QuoteRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuoteRequest"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    phone: string
    message: string
    productId: string | null
    createdAt: Date
  }, ExtArgs["result"]["quoteRequest"]>
  composites: {}
}

export type QuoteRequestGetPayload<S extends boolean | null | undefined | QuoteRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload, S>

export type QuoteRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuoteRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuoteRequestCountAggregateInputType | true
  }

export interface QuoteRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuoteRequest'], meta: { name: 'QuoteRequest' } }
  /**
   * Find zero or one QuoteRequest that matches the filter.
   * @param {QuoteRequestFindUniqueArgs} args - Arguments to find a QuoteRequest
   * @example
   * // Get one QuoteRequest
   * const quoteRequest = await prisma.quoteRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuoteRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, QuoteRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuoteRequestClient<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuoteRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuoteRequestFindUniqueOrThrowArgs} args - Arguments to find a QuoteRequest
   * @example
   * // Get one QuoteRequest
   * const quoteRequest = await prisma.quoteRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuoteRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuoteRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuoteRequestClient<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuoteRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteRequestFindFirstArgs} args - Arguments to find a QuoteRequest
   * @example
   * // Get one QuoteRequest
   * const quoteRequest = await prisma.quoteRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuoteRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, QuoteRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuoteRequestClient<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuoteRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteRequestFindFirstOrThrowArgs} args - Arguments to find a QuoteRequest
   * @example
   * // Get one QuoteRequest
   * const quoteRequest = await prisma.quoteRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuoteRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuoteRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuoteRequestClient<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuoteRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuoteRequests
   * const quoteRequests = await prisma.quoteRequest.findMany()
   * 
   * // Get first 10 QuoteRequests
   * const quoteRequests = await prisma.quoteRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const quoteRequestWithIdOnly = await prisma.quoteRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuoteRequestFindManyArgs>(args?: Prisma.SelectSubset<T, QuoteRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuoteRequest.
   * @param {QuoteRequestCreateArgs} args - Arguments to create a QuoteRequest.
   * @example
   * // Create one QuoteRequest
   * const QuoteRequest = await prisma.quoteRequest.create({
   *   data: {
   *     // ... data to create a QuoteRequest
   *   }
   * })
   * 
   */
  create<T extends QuoteRequestCreateArgs>(args: Prisma.SelectSubset<T, QuoteRequestCreateArgs<ExtArgs>>): Prisma.Prisma__QuoteRequestClient<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuoteRequests.
   * @param {QuoteRequestCreateManyArgs} args - Arguments to create many QuoteRequests.
   * @example
   * // Create many QuoteRequests
   * const quoteRequest = await prisma.quoteRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuoteRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, QuoteRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuoteRequests and returns the data saved in the database.
   * @param {QuoteRequestCreateManyAndReturnArgs} args - Arguments to create many QuoteRequests.
   * @example
   * // Create many QuoteRequests
   * const quoteRequest = await prisma.quoteRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuoteRequests and only return the `id`
   * const quoteRequestWithIdOnly = await prisma.quoteRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuoteRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuoteRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuoteRequest.
   * @param {QuoteRequestDeleteArgs} args - Arguments to delete one QuoteRequest.
   * @example
   * // Delete one QuoteRequest
   * const QuoteRequest = await prisma.quoteRequest.delete({
   *   where: {
   *     // ... filter to delete one QuoteRequest
   *   }
   * })
   * 
   */
  delete<T extends QuoteRequestDeleteArgs>(args: Prisma.SelectSubset<T, QuoteRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__QuoteRequestClient<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuoteRequest.
   * @param {QuoteRequestUpdateArgs} args - Arguments to update one QuoteRequest.
   * @example
   * // Update one QuoteRequest
   * const quoteRequest = await prisma.quoteRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuoteRequestUpdateArgs>(args: Prisma.SelectSubset<T, QuoteRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__QuoteRequestClient<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuoteRequests.
   * @param {QuoteRequestDeleteManyArgs} args - Arguments to filter QuoteRequests to delete.
   * @example
   * // Delete a few QuoteRequests
   * const { count } = await prisma.quoteRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuoteRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuoteRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuoteRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuoteRequests
   * const quoteRequest = await prisma.quoteRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuoteRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, QuoteRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuoteRequests and returns the data updated in the database.
   * @param {QuoteRequestUpdateManyAndReturnArgs} args - Arguments to update many QuoteRequests.
   * @example
   * // Update many QuoteRequests
   * const quoteRequest = await prisma.quoteRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuoteRequests and only return the `id`
   * const quoteRequestWithIdOnly = await prisma.quoteRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuoteRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuoteRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuoteRequest.
   * @param {QuoteRequestUpsertArgs} args - Arguments to update or create a QuoteRequest.
   * @example
   * // Update or create a QuoteRequest
   * const quoteRequest = await prisma.quoteRequest.upsert({
   *   create: {
   *     // ... data to create a QuoteRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuoteRequest we want to update
   *   }
   * })
   */
  upsert<T extends QuoteRequestUpsertArgs>(args: Prisma.SelectSubset<T, QuoteRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__QuoteRequestClient<runtime.Types.Result.GetResult<Prisma.$QuoteRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuoteRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteRequestCountArgs} args - Arguments to filter QuoteRequests to count.
   * @example
   * // Count the number of QuoteRequests
   * const count = await prisma.quoteRequest.count({
   *   where: {
   *     // ... the filter for the QuoteRequests we want to count
   *   }
   * })
  **/
  count<T extends QuoteRequestCountArgs>(
    args?: Prisma.Subset<T, QuoteRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuoteRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuoteRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuoteRequestAggregateArgs>(args: Prisma.Subset<T, QuoteRequestAggregateArgs>): Prisma.PrismaPromise<GetQuoteRequestAggregateType<T>>

  /**
   * Group by QuoteRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuoteRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuoteRequestGroupByArgs['orderBy'] }
      : { orderBy?: QuoteRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuoteRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuoteRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuoteRequest model
 */
readonly fields: QuoteRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuoteRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuoteRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.QuoteRequest$productArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuoteRequest$productArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuoteRequest model
 */
export interface QuoteRequestFieldRefs {
  readonly id: Prisma.FieldRef<"QuoteRequest", 'String'>
  readonly name: Prisma.FieldRef<"QuoteRequest", 'String'>
  readonly email: Prisma.FieldRef<"QuoteRequest", 'String'>
  readonly phone: Prisma.FieldRef<"QuoteRequest", 'String'>
  readonly message: Prisma.FieldRef<"QuoteRequest", 'String'>
  readonly productId: Prisma.FieldRef<"QuoteRequest", 'String'>
  readonly createdAt: Prisma.FieldRef<"QuoteRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuoteRequest findUnique
 */
export type QuoteRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * Filter, which QuoteRequest to fetch.
   */
  where: Prisma.QuoteRequestWhereUniqueInput
}

/**
 * QuoteRequest findUniqueOrThrow
 */
export type QuoteRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * Filter, which QuoteRequest to fetch.
   */
  where: Prisma.QuoteRequestWhereUniqueInput
}

/**
 * QuoteRequest findFirst
 */
export type QuoteRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * Filter, which QuoteRequest to fetch.
   */
  where?: Prisma.QuoteRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuoteRequests to fetch.
   */
  orderBy?: Prisma.QuoteRequestOrderByWithRelationInput | Prisma.QuoteRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuoteRequests.
   */
  cursor?: Prisma.QuoteRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuoteRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuoteRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuoteRequests.
   */
  distinct?: Prisma.QuoteRequestScalarFieldEnum | Prisma.QuoteRequestScalarFieldEnum[]
}

/**
 * QuoteRequest findFirstOrThrow
 */
export type QuoteRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * Filter, which QuoteRequest to fetch.
   */
  where?: Prisma.QuoteRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuoteRequests to fetch.
   */
  orderBy?: Prisma.QuoteRequestOrderByWithRelationInput | Prisma.QuoteRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuoteRequests.
   */
  cursor?: Prisma.QuoteRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuoteRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuoteRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuoteRequests.
   */
  distinct?: Prisma.QuoteRequestScalarFieldEnum | Prisma.QuoteRequestScalarFieldEnum[]
}

/**
 * QuoteRequest findMany
 */
export type QuoteRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * Filter, which QuoteRequests to fetch.
   */
  where?: Prisma.QuoteRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuoteRequests to fetch.
   */
  orderBy?: Prisma.QuoteRequestOrderByWithRelationInput | Prisma.QuoteRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuoteRequests.
   */
  cursor?: Prisma.QuoteRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuoteRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuoteRequests.
   */
  skip?: number
  distinct?: Prisma.QuoteRequestScalarFieldEnum | Prisma.QuoteRequestScalarFieldEnum[]
}

/**
 * QuoteRequest create
 */
export type QuoteRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a QuoteRequest.
   */
  data: Prisma.XOR<Prisma.QuoteRequestCreateInput, Prisma.QuoteRequestUncheckedCreateInput>
}

/**
 * QuoteRequest createMany
 */
export type QuoteRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuoteRequests.
   */
  data: Prisma.QuoteRequestCreateManyInput | Prisma.QuoteRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuoteRequest createManyAndReturn
 */
export type QuoteRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * The data used to create many QuoteRequests.
   */
  data: Prisma.QuoteRequestCreateManyInput | Prisma.QuoteRequestCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuoteRequest update
 */
export type QuoteRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a QuoteRequest.
   */
  data: Prisma.XOR<Prisma.QuoteRequestUpdateInput, Prisma.QuoteRequestUncheckedUpdateInput>
  /**
   * Choose, which QuoteRequest to update.
   */
  where: Prisma.QuoteRequestWhereUniqueInput
}

/**
 * QuoteRequest updateMany
 */
export type QuoteRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuoteRequests.
   */
  data: Prisma.XOR<Prisma.QuoteRequestUpdateManyMutationInput, Prisma.QuoteRequestUncheckedUpdateManyInput>
  /**
   * Filter which QuoteRequests to update
   */
  where?: Prisma.QuoteRequestWhereInput
  /**
   * Limit how many QuoteRequests to update.
   */
  limit?: number
}

/**
 * QuoteRequest updateManyAndReturn
 */
export type QuoteRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * The data used to update QuoteRequests.
   */
  data: Prisma.XOR<Prisma.QuoteRequestUpdateManyMutationInput, Prisma.QuoteRequestUncheckedUpdateManyInput>
  /**
   * Filter which QuoteRequests to update
   */
  where?: Prisma.QuoteRequestWhereInput
  /**
   * Limit how many QuoteRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuoteRequest upsert
 */
export type QuoteRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the QuoteRequest to update in case it exists.
   */
  where: Prisma.QuoteRequestWhereUniqueInput
  /**
   * In case the QuoteRequest found by the `where` argument doesn't exist, create a new QuoteRequest with this data.
   */
  create: Prisma.XOR<Prisma.QuoteRequestCreateInput, Prisma.QuoteRequestUncheckedCreateInput>
  /**
   * In case the QuoteRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuoteRequestUpdateInput, Prisma.QuoteRequestUncheckedUpdateInput>
}

/**
 * QuoteRequest delete
 */
export type QuoteRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
  /**
   * Filter which QuoteRequest to delete.
   */
  where: Prisma.QuoteRequestWhereUniqueInput
}

/**
 * QuoteRequest deleteMany
 */
export type QuoteRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuoteRequests to delete
   */
  where?: Prisma.QuoteRequestWhereInput
  /**
   * Limit how many QuoteRequests to delete.
   */
  limit?: number
}

/**
 * QuoteRequest.product
 */
export type QuoteRequest$productArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
}

/**
 * QuoteRequest without action
 */
export type QuoteRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuoteRequest
   */
  select?: Prisma.QuoteRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuoteRequest
   */
  omit?: Prisma.QuoteRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuoteRequestInclude<ExtArgs> | null
}
