import {
  Archive,
  BookOpen,
  Box,
  Boxes,
  BrickWall,
  Cake,
  Candy,
  Car,
  Cigarette,
  Coffee,
  Columns3,
  Cookie,
  Copy,
  Cpu,
  Cylinder,
  DoorOpen,
  Droplets,
  Flame,
  Flower2,
  Frame,
  Gift,
  Grid3x3,
  Hammer,
  Hexagon,
  Layers,
  Leaf,
  LayoutGrid,
  Package,
  PackageOpen,
  PanelTop,
  Pill,
  Pizza,
  Scissors,
  Sheet,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  SquareStack,
  Store,
  Trophy,
  UtensilsCrossed,
  Watch,
  Wine,
} from 'lucide-react'

/**
 * Keyword → Lucide icon for mega-menu subcategories.
 * More specific rules must come first.
 */
const RULES = [
  // —— Boxes by style ——
  { test: /book\s*style|book.?box/i, icon: BookOpen },
  { test: /counter/i, icon: Store },
  { test: /die.?cut/i, icon: Scissors },
  { test: /display/i, icon: LayoutGrid },
  { test: /drawer/i, icon: PanelTop },
  { test: /hexagon|hex\b/i, icon: Hexagon },
  { test: /hinged|hinge/i, icon: DoorOpen },
  { test: /shoulder|neck/i, icon: Cylinder },
  { test: /telescope|telescop/i, icon: Copy },
  { test: /mailer|sleeve/i, icon: PackageOpen },
  { test: /folding|fold/i, icon: SquareStack },
  { test: /window/i, icon: Frame },
  { test: /gable/i, icon: Archive },

  // —— Boxes by material ——
  { test: /cardboard/i, icon: Box },
  { test: /chipboard/i, icon: Layers },
  { test: /corrugat/i, icon: Columns3 },
  { test: /kraft/i, icon: Sheet },
  { test: /paperboard/i, icon: Layers },
  { test: /plastic/i, icon: Grid3x3 },
  { test: /rigid/i, icon: BrickWall },
  { test: /wood|wooden/i, icon: Boxes },
  { test: /metal|tin/i, icon: Cylinder },
  { test: /foam/i, icon: SquareStack },

  // —— Boxes by industry ——
  { test: /apparel|cloth|shirt|fashion|garment/i, icon: Shirt },
  { test: /bakery|bread|cake|pastry|dessert/i, icon: Cake },
  { test: /pizza/i, icon: Pizza },
  { test: /cookie|biscuit/i, icon: Cookie },
  { test: /candy|chocolate|sweet|confection/i, icon: Candy },
  { test: /food|meal|snack|cereal|grocery/i, icon: UtensilsCrossed },
  { test: /bottle|wine|beverage|drink/i, icon: Wine },
  { test: /coffee|tea/i, icon: Coffee },
  { test: /candle/i, icon: Flame },
  { test: /cosmetic|beauty|makeup|skincare/i, icon: Sparkles },
  { test: /perfume|fragrance/i, icon: Sparkles },
  { test: /soap|bath|wash/i, icon: Droplets },
  { test: /jewelry|jewellery|ring|necklace/i, icon: Flower2 },
  { test: /watch/i, icon: Watch },
  { test: /shoe|footwear|sneaker/i, icon: ShoppingBag },
  { test: /sport|fitness|gym/i, icon: Trophy },
  { test: /gift|present|holiday|christmas/i, icon: Gift },
  { test: /electronic|gadget|device|tech|phone|mobile/i, icon: Smartphone },
  { test: /computer|cpu|laptop/i, icon: Cpu },
  { test: /shipping|courier|delivery/i, icon: Package },
  { test: /stationery|office/i, icon: BookOpen },
  { test: /auto|car|vehicle|parts/i, icon: Car },
  { test: /hardware|tool/i, icon: Hammer },
  { test: /pharma|medicine|pill|health|medical/i, icon: Pill },
  { test: /kitchen|ware|cook/i, icon: UtensilsCrossed },
  { test: /vape|cbd|hemp|cannabis|pre.?roll/i, icon: Leaf },
  { test: /cigarette|tobacco|smoke/i, icon: Cigarette },
  { test: /spice|season/i, icon: Flame },
  { test: /product\s*boxes?/i, icon: Box },
  { test: /retail/i, icon: Store },
]

export function getSubcategoryIcon(name = '') {
  const matched = RULES.find((rule) => rule.test.test(String(name)))
  return matched?.icon || Package
}
